#!/bin/sh
##PBS -q normal
#PBS -N cookbook1
#PBS -o %N.out
#PBS -e %N.err
# Mail Directives
##PBS -m abe
##PBS -M me@colorado.edu
 
#PBS -l walltime=01:00:00
##PBS -l pmem=100mb
#PBS -l nodes=1:ppn=4
 
 
NCPU=`wc -l < $PBS_NODEFILE`
NNODES=`uniq $PBS_NODEFILE | wc -l`
MPIPREFIX=/usr/local/mvapich2-1.9rc1-intel11
MPIRUN=$MPIPREFIX/bin/mpirun_rsh
 
echo "Running on nodes " `uniq $PBS_NODEFILE`
echo "Number of available cpus " $NCPU
echo "Number of available nodes " $NNODES
 
$MPIRUN -np $NCPU -hostfile $PBS_NODEFILE ~/opt/snac/build/bin/Snac ./cookbook1.xml 
